2022-02-07 16:16:22,286 [WARNING] django.request: Method Not Allowed: /social/google/login
2022-02-07 16:21:58,616 [WARNING] django.request: Method Not Allowed: /social/google/login
2022-02-07 16:22:17,368 [WARNING] django.request: Method Not Allowed: /social/google/login
2022-02-07 17:02:42,602 [WARNING] django.request: Method Not Allowed: /social/google/login
2022-02-09 15:34:54,244 [WARNING] django.request: Not Found: /8000proudct/main/newegg
2022-02-09 15:35:59,420 [WARNING] django.request: Not Found: /8000product/main/newegg
2022-02-09 15:36:48,397 [WARNING] django.request: Not Found: /productmain/newegg
2022-02-09 18:01:53,035 [WARNING] django.request: Unauthorized: /product/main/amazon
2022-02-09 21:09:08,583 [ERROR] django.request: Internal Server Error: /product/like/delete
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\projectAn\likeAN\views.py", line 60, in post
    serializer.destroy()
TypeError: destroy() missing 1 required positional argument: 'validated_data'
2022-02-09 21:16:53,549 [ERROR] django.request: Internal Server Error: /product/like/delete
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\projectAn\likeAN\views.py", line 60, in post
    serializer.destroy()
AttributeError: 'AddLikeSerializer' object has no attribute 'destroy'
2022-02-09 21:35:08,146 [WARNING] django.request: Bad Request: /product/like/delete
2022-02-09 21:35:47,304 [WARNING] django.request: Bad Request: /product/like/delete
2022-02-09 21:35:58,735 [WARNING] django.request: Bad Request: /product/like/delete
2022-02-09 21:38:08,613 [WARNING] django.request: Bad Request: /product/like/delete
2022-02-09 21:38:19,842 [WARNING] django.request: Bad Request: /product/like/delete
2022-02-09 21:40:41,994 [WARNING] django.request: Bad Request: /product/like/delete
2022-02-09 21:40:53,389 [WARNING] django.request: Bad Request: /product/like/delete
2022-02-09 21:41:31,544 [WARNING] django.request: Bad Request: /product/like/delete
2022-02-09 21:41:42,681 [WARNING] django.request: Bad Request: /product/like/delete
2022-02-09 21:43:13,214 [WARNING] django.request: Bad Request: /product/like/delete
2022-02-09 21:45:37,081 [WARNING] django.request: Bad Request: /product/like/delete
2022-02-16 15:15:36,611 [ERROR] django.request: Internal Server Error: /product/list/amazon
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\ListView.py", line 28, in get
    paginated_queryset = self.paginate_queryset(queryset, request)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\pagination.py", line 642, in paginate_queryset
    results = list(queryset[offset:offset + self.page_size + 1])
  File "D:\study\projectAN\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "D:\study\projectAN\venv\lib\site-packages\django\db\models\query.py", line 1356, in _fetch_all
    self._prefetch_related_objects()
  File "D:\study\projectAN\venv\lib\site-packages\django\db\models\query.py", line 841, in _prefetch_related_objects
    prefetch_related_objects(self._result_cache, *self._prefetch_related_lookups)
  File "D:\study\projectAN\venv\lib\site-packages\django\db\models\query.py", line 1743, in prefetch_related_objects
    raise AttributeError("Cannot find '%s' on %s object, '%s' is an invalid "
AttributeError: Cannot find 'price' on Product object, 'price' is an invalid parameter to prefetch_related()
2022-02-16 15:15:47,882 [ERROR] django.request: Internal Server Error: /product/list/amazon
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\ListView.py", line 30, in get
    response = self.get_paginated_response(data=serializer.data)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in <listcomp>
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\fields.py", line 1886, in to_representation
    return method(value)
  File "D:\study\projectAN\projectAN\AN\serializer.py", line 11, in get_price_prefetch
    prices = price.price.all()
AttributeError: 'Product' object has no attribute 'price'
2022-02-16 15:15:59,462 [ERROR] django.request: Internal Server Error: /product/list/newegg
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\ListView.py", line 28, in get
    paginated_queryset = self.paginate_queryset(queryset, request)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\pagination.py", line 642, in paginate_queryset
    results = list(queryset[offset:offset + self.page_size + 1])
  File "D:\study\projectAN\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "D:\study\projectAN\venv\lib\site-packages\django\db\models\query.py", line 1356, in _fetch_all
    self._prefetch_related_objects()
  File "D:\study\projectAN\venv\lib\site-packages\django\db\models\query.py", line 841, in _prefetch_related_objects
    prefetch_related_objects(self._result_cache, *self._prefetch_related_lookups)
  File "D:\study\projectAN\venv\lib\site-packages\django\db\models\query.py", line 1743, in prefetch_related_objects
    raise AttributeError("Cannot find '%s' on %s object, '%s' is an invalid "
AttributeError: Cannot find 'price' on Product object, 'price' is an invalid parameter to prefetch_related()
2022-02-16 15:16:10,766 [ERROR] django.request: Internal Server Error: /product/list/newegg
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\ListView.py", line 30, in get
    response = self.get_paginated_response(data=serializer.data)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in <listcomp>
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\fields.py", line 1886, in to_representation
    return method(value)
  File "D:\study\projectAN\projectAN\AN\serializer.py", line 11, in get_price_prefetch
    prices = price.price.all()
AttributeError: 'Product' object has no attribute 'price'
2022-02-16 15:16:52,243 [ERROR] django.request: Internal Server Error: /product/list/amazon
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\ListView.py", line 30, in get
    response = self.get_paginated_response(data=serializer.data)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in <listcomp>
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\fields.py", line 1886, in to_representation
    return method(value)
  File "D:\study\projectAN\projectAN\AN\serializer.py", line 11, in get_price_prefetch
    prices = price.price.all()
AttributeError: 'Product' object has no attribute 'price'
2022-02-16 15:17:03,717 [ERROR] django.request: Internal Server Error: /product/list/amazon
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\ListView.py", line 30, in get
    response = self.get_paginated_response(data=serializer.data)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in <listcomp>
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\fields.py", line 1886, in to_representation
    return method(value)
  File "D:\study\projectAN\projectAN\AN\serializer.py", line 11, in get_price_prefetch
    prices = price.price.all()
AttributeError: 'Product' object has no attribute 'price'
2022-02-16 15:17:15,566 [ERROR] django.request: Internal Server Error: /product/list/newegg
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\ListView.py", line 30, in get
    response = self.get_paginated_response(data=serializer.data)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in <listcomp>
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\fields.py", line 1886, in to_representation
    return method(value)
  File "D:\study\projectAN\projectAN\AN\serializer.py", line 11, in get_price_prefetch
    prices = price.price.all()
AttributeError: 'Product' object has no attribute 'price'
2022-02-16 15:17:27,410 [ERROR] django.request: Internal Server Error: /product/list/newegg
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\ListView.py", line 30, in get
    response = self.get_paginated_response(data=serializer.data)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in <listcomp>
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\fields.py", line 1886, in to_representation
    return method(value)
  File "D:\study\projectAN\projectAN\AN\serializer.py", line 11, in get_price_prefetch
    prices = price.price.all()
AttributeError: 'Product' object has no attribute 'price'
2022-02-16 15:18:24,322 [ERROR] django.request: Internal Server Error: /product/main/amazon
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\silk\profiling\profiler.py", line 161, in wrapped_target
    result = target(*args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\MainView.py", line 35, in get
    response = Response(data=serializer.data, status=status.HTTP_200_OK)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in <listcomp>
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\fields.py", line 1886, in to_representation
    return method(value)
  File "D:\study\projectAN\projectAN\AN\serializer.py", line 11, in get_price_prefetch
    prices = price.price.all()
AttributeError: 'Product' object has no attribute 'price'
2022-02-16 15:18:36,028 [ERROR] django.request: Internal Server Error: /product/main/amazon
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\silk\profiling\profiler.py", line 161, in wrapped_target
    result = target(*args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\MainView.py", line 35, in get
    response = Response(data=serializer.data, status=status.HTTP_200_OK)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in <listcomp>
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\fields.py", line 1886, in to_representation
    return method(value)
  File "D:\study\projectAN\projectAN\AN\serializer.py", line 11, in get_price_prefetch
    prices = price.price.all()
AttributeError: 'Product' object has no attribute 'price'
2022-02-16 15:18:47,940 [ERROR] django.request: Internal Server Error: /product/main/newegg
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\silk\profiling\profiler.py", line 161, in wrapped_target
    result = target(*args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\MainView.py", line 56, in get
    response = Response(data=serializer.data, status=status.HTTP_200_OK)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in <listcomp>
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\fields.py", line 1886, in to_representation
    return method(value)
  File "D:\study\projectAN\projectAN\AN\serializer.py", line 11, in get_price_prefetch
    prices = price.price.all()
AttributeError: 'Product' object has no attribute 'price'
2022-02-16 15:18:59,771 [ERROR] django.request: Internal Server Error: /product/main/newegg
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\silk\profiling\profiler.py", line 161, in wrapped_target
    result = target(*args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\MainView.py", line 56, in get
    response = Response(data=serializer.data, status=status.HTTP_200_OK)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in <listcomp>
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\fields.py", line 1886, in to_representation
    return method(value)
  File "D:\study\projectAN\projectAN\AN\serializer.py", line 11, in get_price_prefetch
    prices = price.price.all()
AttributeError: 'Product' object has no attribute 'price'
2022-02-16 15:20:01,649 [ERROR] django.request: Internal Server Error: /product/main/amazon
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\silk\profiling\profiler.py", line 161, in wrapped_target
    result = target(*args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\MainView.py", line 35, in get
    response = Response(data=serializer.data, status=status.HTTP_200_OK)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in <listcomp>
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\fields.py", line 1886, in to_representation
    return method(value)
  File "D:\study\projectAN\projectAN\AN\serializer.py", line 11, in get_price_prefetch
    prices = price.all()
AttributeError: 'Product' object has no attribute 'all'
2022-02-16 15:20:13,061 [ERROR] django.request: Internal Server Error: /product/main/amazon
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\silk\profiling\profiler.py", line 161, in wrapped_target
    result = target(*args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\MainView.py", line 35, in get
    response = Response(data=serializer.data, status=status.HTTP_200_OK)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in <listcomp>
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\fields.py", line 1886, in to_representation
    return method(value)
  File "D:\study\projectAN\projectAN\AN\serializer.py", line 11, in get_price_prefetch
    prices = price.all()
AttributeError: 'Product' object has no attribute 'all'
2022-02-16 15:20:24,319 [ERROR] django.request: Internal Server Error: /product/main/newegg
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\silk\profiling\profiler.py", line 161, in wrapped_target
    result = target(*args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\MainView.py", line 56, in get
    response = Response(data=serializer.data, status=status.HTTP_200_OK)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in <listcomp>
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\fields.py", line 1886, in to_representation
    return method(value)
  File "D:\study\projectAN\projectAN\AN\serializer.py", line 11, in get_price_prefetch
    prices = price.all()
AttributeError: 'Product' object has no attribute 'all'
2022-02-16 15:20:35,602 [ERROR] django.request: Internal Server Error: /product/main/newegg
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\silk\profiling\profiler.py", line 161, in wrapped_target
    result = target(*args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\MainView.py", line 56, in get
    response = Response(data=serializer.data, status=status.HTTP_200_OK)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in <listcomp>
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\fields.py", line 1886, in to_representation
    return method(value)
  File "D:\study\projectAN\projectAN\AN\serializer.py", line 11, in get_price_prefetch
    prices = price.all()
AttributeError: 'Product' object has no attribute 'all'
2022-02-16 15:26:20,565 [ERROR] django.request: Internal Server Error: /product/main/amazon
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\silk\profiling\profiler.py", line 161, in wrapped_target
    result = target(*args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\MainView.py", line 35, in get
    response = Response(data=serializer.data, status=status.HTTP_200_OK)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in <listcomp>
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\fields.py", line 1886, in to_representation
    return method(value)
  File "D:\study\projectAN\projectAN\AN\serializer.py", line 11, in get_price_prefetch
    prices = productObj.price.all()
AttributeError: 'Product' object has no attribute 'price'
2022-02-16 15:26:31,740 [ERROR] django.request: Internal Server Error: /product/main/amazon
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\silk\profiling\profiler.py", line 161, in wrapped_target
    result = target(*args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\MainView.py", line 35, in get
    response = Response(data=serializer.data, status=status.HTTP_200_OK)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in <listcomp>
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\fields.py", line 1886, in to_representation
    return method(value)
  File "D:\study\projectAN\projectAN\AN\serializer.py", line 11, in get_price_prefetch
    prices = productObj.price.all()
AttributeError: 'Product' object has no attribute 'price'
2022-02-16 15:26:43,003 [ERROR] django.request: Internal Server Error: /product/main/newegg
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\silk\profiling\profiler.py", line 161, in wrapped_target
    result = target(*args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\MainView.py", line 56, in get
    response = Response(data=serializer.data, status=status.HTTP_200_OK)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in <listcomp>
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\fields.py", line 1886, in to_representation
    return method(value)
  File "D:\study\projectAN\projectAN\AN\serializer.py", line 11, in get_price_prefetch
    prices = productObj.price.all()
AttributeError: 'Product' object has no attribute 'price'
2022-02-16 15:26:54,356 [ERROR] django.request: Internal Server Error: /product/main/newegg
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\silk\profiling\profiler.py", line 161, in wrapped_target
    result = target(*args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\MainView.py", line 56, in get
    response = Response(data=serializer.data, status=status.HTTP_200_OK)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in <listcomp>
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\fields.py", line 1886, in to_representation
    return method(value)
  File "D:\study\projectAN\projectAN\AN\serializer.py", line 11, in get_price_prefetch
    prices = productObj.price.all()
AttributeError: 'Product' object has no attribute 'price'
2022-02-16 15:28:43,025 [ERROR] django.request: Internal Server Error: /product/list/amazon
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\ListView.py", line 30, in get
    response = self.get_paginated_response(data=serializer.data)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in <listcomp>
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\fields.py", line 1886, in to_representation
    return method(value)
  File "D:\study\projectAN\projectAN\AN\serializer.py", line 11, in get_price_prefetch
    prices = productObj.price.all()
AttributeError: 'Product' object has no attribute 'price'
2022-02-16 15:29:03,070 [ERROR] django.request: Internal Server Error: /product/list/amazon
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\ListView.py", line 30, in get
    response = self.get_paginated_response(data=serializer.data)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in <listcomp>
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\fields.py", line 1886, in to_representation
    return method(value)
  File "D:\study\projectAN\projectAN\AN\serializer.py", line 11, in get_price_prefetch
    prices = productObj.prices.all()
AttributeError: 'list' object has no attribute 'all'
2022-02-16 15:29:14,493 [ERROR] django.request: Internal Server Error: /product/list/amazon
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\ListView.py", line 30, in get
    response = self.get_paginated_response(data=serializer.data)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in <listcomp>
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\fields.py", line 1886, in to_representation
    return method(value)
  File "D:\study\projectAN\projectAN\AN\serializer.py", line 11, in get_price_prefetch
    prices = productObj.prices.all()
AttributeError: 'Product' object has no attribute 'prices'
2022-02-16 15:29:25,801 [ERROR] django.request: Internal Server Error: /product/list/newegg
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\ListView.py", line 30, in get
    response = self.get_paginated_response(data=serializer.data)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in <listcomp>
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\fields.py", line 1886, in to_representation
    return method(value)
  File "D:\study\projectAN\projectAN\AN\serializer.py", line 11, in get_price_prefetch
    prices = productObj.prices.all()
AttributeError: 'list' object has no attribute 'all'
2022-02-16 15:29:36,940 [ERROR] django.request: Internal Server Error: /product/list/newegg
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\ListView.py", line 30, in get
    response = self.get_paginated_response(data=serializer.data)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in <listcomp>
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\fields.py", line 1886, in to_representation
    return method(value)
  File "D:\study\projectAN\projectAN\AN\serializer.py", line 11, in get_price_prefetch
    prices = productObj.prices.all()
AttributeError: 'Product' object has no attribute 'prices'
2022-02-16 15:30:25,222 [ERROR] django.request: Internal Server Error: /product/list/amazon
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\ListView.py", line 30, in get
    response = self.get_paginated_response(data=serializer.data)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in <listcomp>
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\fields.py", line 1886, in to_representation
    return method(value)
  File "D:\study\projectAN\projectAN\AN\serializer.py", line 11, in get_price_prefetch
    prices = productObj.PriceInfo.all()
AttributeError: 'Product' object has no attribute 'PriceInfo'
2022-02-16 15:30:36,391 [ERROR] django.request: Internal Server Error: /product/list/amazon
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\ListView.py", line 30, in get
    response = self.get_paginated_response(data=serializer.data)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in <listcomp>
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\fields.py", line 1886, in to_representation
    return method(value)
  File "D:\study\projectAN\projectAN\AN\serializer.py", line 11, in get_price_prefetch
    prices = productObj.PriceInfo.all()
AttributeError: 'Product' object has no attribute 'PriceInfo'
2022-02-16 15:30:57,693 [ERROR] django.request: Internal Server Error: /product/list/amazon
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\ListView.py", line 30, in get
    response = self.get_paginated_response(data=serializer.data)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in <listcomp>
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\fields.py", line 1886, in to_representation
    return method(value)
  File "D:\study\projectAN\projectAN\AN\serializer.py", line 11, in get_price_prefetch
    prices = productObj.prices
AttributeError: 'Product' object has no attribute 'prices'
2022-02-16 15:31:09,055 [ERROR] django.request: Internal Server Error: /product/list/amazon
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\ListView.py", line 30, in get
    response = self.get_paginated_response(data=serializer.data)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in <listcomp>
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\fields.py", line 1886, in to_representation
    return method(value)
  File "D:\study\projectAN\projectAN\AN\serializer.py", line 11, in get_price_prefetch
    prices = productObj.prices
AttributeError: 'Product' object has no attribute 'prices'
2022-02-16 15:31:20,585 [ERROR] django.request: Internal Server Error: /product/list/newegg
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\ListView.py", line 30, in get
    response = self.get_paginated_response(data=serializer.data)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in <listcomp>
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\fields.py", line 1886, in to_representation
    return method(value)
  File "D:\study\projectAN\projectAN\AN\serializer.py", line 11, in get_price_prefetch
    prices = productObj.prices
AttributeError: 'Product' object has no attribute 'prices'
2022-02-16 15:31:31,983 [ERROR] django.request: Internal Server Error: /product/list/newegg
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\ListView.py", line 30, in get
    response = self.get_paginated_response(data=serializer.data)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in <listcomp>
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\fields.py", line 1886, in to_representation
    return method(value)
  File "D:\study\projectAN\projectAN\AN\serializer.py", line 11, in get_price_prefetch
    prices = productObj.prices
AttributeError: 'Product' object has no attribute 'prices'
2022-02-16 15:32:47,651 [ERROR] django.request: Internal Server Error: /product/list/amazon
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\ListView.py", line 30, in get
    response = self.get_paginated_response(data=serializer.data)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in <listcomp>
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\fields.py", line 1886, in to_representation
    return method(value)
  File "D:\study\projectAN\projectAN\AN\serializer.py", line 11, in get_price_prefetch
    prices = productObj.prices
AttributeError: 'Product' object has no attribute 'prices'
2022-02-16 15:32:58,885 [ERROR] django.request: Internal Server Error: /product/list/amazon
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\ListView.py", line 30, in get
    response = self.get_paginated_response(data=serializer.data)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in <listcomp>
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\fields.py", line 1886, in to_representation
    return method(value)
  File "D:\study\projectAN\projectAN\AN\serializer.py", line 11, in get_price_prefetch
    prices = productObj.prices
AttributeError: 'Product' object has no attribute 'prices'
2022-02-16 15:33:10,066 [ERROR] django.request: Internal Server Error: /product/list/newegg
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\ListView.py", line 30, in get
    response = self.get_paginated_response(data=serializer.data)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in <listcomp>
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\fields.py", line 1886, in to_representation
    return method(value)
  File "D:\study\projectAN\projectAN\AN\serializer.py", line 11, in get_price_prefetch
    prices = productObj.prices
AttributeError: 'Product' object has no attribute 'prices'
2022-02-16 15:33:21,334 [ERROR] django.request: Internal Server Error: /product/list/newegg
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\ListView.py", line 30, in get
    response = self.get_paginated_response(data=serializer.data)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in <listcomp>
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\fields.py", line 1886, in to_representation
    return method(value)
  File "D:\study\projectAN\projectAN\AN\serializer.py", line 11, in get_price_prefetch
    prices = productObj.prices
AttributeError: 'Product' object has no attribute 'prices'
2022-02-16 15:36:40,343 [ERROR] django.request: Internal Server Error: /product/list/amazon
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\ListView.py", line 30, in get
    response = self.get_paginated_response(data=serializer.data)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in <listcomp>
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\fields.py", line 1886, in to_representation
    return method(value)
  File "D:\study\projectAN\projectAN\AN\serializer.py", line 11, in get_price_prefetch
    prices = productObj.prices
AttributeError: 'Product' object has no attribute 'prices'
2022-02-16 15:36:51,641 [ERROR] django.request: Internal Server Error: /product/list/amazon
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\ListView.py", line 30, in get
    response = self.get_paginated_response(data=serializer.data)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in <listcomp>
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\fields.py", line 1886, in to_representation
    return method(value)
  File "D:\study\projectAN\projectAN\AN\serializer.py", line 11, in get_price_prefetch
    prices = productObj.prices
AttributeError: 'Product' object has no attribute 'prices'
2022-02-16 15:37:03,479 [ERROR] django.request: Internal Server Error: /product/list/newegg
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\ListView.py", line 30, in get
    response = self.get_paginated_response(data=serializer.data)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in <listcomp>
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\fields.py", line 1886, in to_representation
    return method(value)
  File "D:\study\projectAN\projectAN\AN\serializer.py", line 11, in get_price_prefetch
    prices = productObj.prices
AttributeError: 'Product' object has no attribute 'prices'
2022-02-16 15:37:14,837 [ERROR] django.request: Internal Server Error: /product/list/newegg
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\ListView.py", line 30, in get
    response = self.get_paginated_response(data=serializer.data)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 686, in <listcomp>
    return [
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\fields.py", line 1886, in to_representation
    return method(value)
  File "D:\study\projectAN\projectAN\AN\serializer.py", line 11, in get_price_prefetch
    prices = productObj.prices
AttributeError: 'Product' object has no attribute 'prices'
2022-02-16 16:16:04,267 [ERROR] django.request: Internal Server Error: /product/detail
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\DetailView.py", line 32, in post
    serializer = productSerializer(queryset[0], many=False)
  File "D:\study\projectAN\venv\lib\site-packages\django\db\models\query.py", line 322, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
2022-02-16 16:16:04,426 [ERROR] django.request: Internal Server Error: /product/detail
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\DetailView.py", line 32, in post
    serializer = productSerializer(queryset[0], many=False)
  File "D:\study\projectAN\venv\lib\site-packages\django\db\models\query.py", line 322, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
2022-02-16 16:16:36,536 [ERROR] django.request: Internal Server Error: /product/detail
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\DetailView.py", line 32, in post
    serializer = productSerializer(queryset[0], many=False)
  File "D:\study\projectAN\venv\lib\site-packages\django\db\models\query.py", line 322, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
2022-02-16 16:16:36,691 [ERROR] django.request: Internal Server Error: /product/detail
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\DetailView.py", line 32, in post
    serializer = productSerializer(queryset[0], many=False)
  File "D:\study\projectAN\venv\lib\site-packages\django\db\models\query.py", line 322, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
2022-02-16 16:17:57,422 [ERROR] django.request: Internal Server Error: /product/detail
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\DetailView.py", line 33, in post
    serializer = productSerializer(queryset[0], many=False)
  File "D:\study\projectAN\venv\lib\site-packages\django\db\models\query.py", line 322, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
2022-02-16 16:17:57,587 [ERROR] django.request: Internal Server Error: /product/detail
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\DetailView.py", line 33, in post
    serializer = productSerializer(queryset[0], many=False)
  File "D:\study\projectAN\venv\lib\site-packages\django\db\models\query.py", line 322, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
2022-02-16 16:18:56,157 [ERROR] django.request: Internal Server Error: /product/detail
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\DetailView.py", line 33, in post
    serializer = productSerializer(queryset[0], many=False)
  File "D:\study\projectAN\venv\lib\site-packages\django\db\models\query.py", line 322, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
2022-02-16 16:18:56,340 [ERROR] django.request: Internal Server Error: /product/detail
Traceback (most recent call last):
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\study\projectAN\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\study\projectAN\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\study\projectAN\projectAN\AN\views\DetailView.py", line 33, in post
    serializer = productSerializer(queryset[0], many=False)
  File "D:\study\projectAN\venv\lib\site-packages\django\db\models\query.py", line 322, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
